wallpaper{
    monitor = eDP-1
    path = ~/photos/wallpapers/beach.png
}

wallpaper{
    monitor = HDMI-A-3
    path = ~/photos/wallpapers/goth_gf_wallpaper.png
}


wallpaper{
    monitor = DP-4
    path = ~/photos/wallpapers/gothic_vampire.png
}
splash = false
ipc = true
